#!/bin/sh
#
# Run this script to generate the build system
#

OS=$(uname -s)

if [ ! "$OS" = "Darwin" ]
then
    libtoolize
else
    glibtoolize
fi
aclocal
autoheader
automake --add-missing
autoconf

